dbt_testing:
  target: github_action
  outputs:
    github_action:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dbt_test
      threads: 4
      keyfile_json: "{{ env_var('GCP_KEYFILE_JSON') | as_native }}"
