dbt_testing:
  target: github_action
  outputs:
    github_action:
      type: bigquery
      method: service-account
      # Forzamos que sea un string explícito
      project: "{{ env_var('GCP_PROJECT_ID') | string }}"
      dataset: dbt_test
      threads: 4
      # Quitamos el filtro as_native y dejamos que dbt lo maneje como JSON puro
      keyfile_json: "{{ env_var('GCP_KEYFILE_JSON') }}"