name: dbt_CI_Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dbt-bigquery

      - name: Run dbt Build
        working-directory: ./first_project
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}
        run: |
          dbt build --profiles-dir .. --target github_action
