name: dbt_CI_Pipeline

on:
  push:
    branches: [ main ]  # Verifica si tu rama se llama main o master
  pull_request:
    branches: [ main ]

jobs:
  run_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dbt-postgres

- name: Run dbt Build
        working-directory: ./first_project
        run: |
          # El punto (.) en --profiles-dir le dice que busque el profiles.yml
          # que copiamos a la raíz del repositorio.
          dbt build --profiles-dir .. --target github_action
        env:
          # Estas son las variables que dbt buscará para BigQuery
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}